version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    networks:
      - raizen-network
    depends_on:
      - db
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./ui
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - raizen-network

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - raizen-network

networks:
  raizen-network:
    driver: bridge

volumes:
  mongo-data:
